FROM scratch
MAINTAINER Rom1 <rom1@canel.ch> - CANEL https://www.canel.ch
ADD rootfs.tar /

LABEL date=""
LABEL version=""
LABEL description=""

RUN apt-get update \
	&& apt-get -y upgrade \
	&& apt-get -y --purge autoremove \
	&& apt-get clean \
	&& find /var/lib/apt/lists -type f -delete \

CMD ["/bin/bash"]
